# -*- coding: utf-8 -*-
"""Janatahack: Independence Day 2020 ML Hackathon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hPzjZPpo1LwguG4KJPghvyDOl2y3RASe
"""

!wget https://datahack-prod.s3.amazonaws.com/test_file/test_8iecVfC.zip
!wget https://datahack-prod.s3.amazonaws.com/train_file/train_tGmol3O.zip
!wget https://datahack-prod.s3.amazonaws.com/sample_submission/sample_submission_UVKGLZE.csv

!unzip train_tGmol3O.zip
!unzip test_8iecVfC.zip

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sub = pd.read_csv('sample_submission_UVKGLZE.csv')

train.head(5)

test.head(5)

sub.head(5)

train.isnull().sum(),test.isnull().sum(),train.shape,test.shape,train.dtypes

#for F1
train['Department']=train['ABSTRACT']+' '+train['TITLE']
test['Department']=test['ABSTRACT']+' '+test['TITLE']
del train['ID']
del test['ID']
del train['ABSTRACT']
del test['ABSTRACT']
del train['TITLE']
del test['TITLE']

train['labels'] = list(zip(train['Computer Science'].tolist(), train['Physics'].tolist(), train['Mathematics'].tolist(), train['Statistics'].tolist(),  train['Quantitative Biology'].tolist(), train['Quantitative Finance'].tolist()))
train['Department'] = train['Department'].apply(lambda x: x.replace('\n', ' '))

!pip install transformers
!pip install tensorboardx
!pip install simpletransformers

from simpletransformers.classification import MultiLabelClassificationModel
model = MultiLabelClassificationModel('roberta', 'roberta-base', num_labels=6, args={'train_batch_size':32, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 6, 'max_seq_length': 256})

model.train_model(train)

to_predict = test.text.apply(lambda x: x.replace('\n', ' ')).tolist()
preds, outputs = model.predict(to_predict)

label_cols = ['Computer Science', 'Physics' , 'Mathematics' , 'Statistics' , 'Quantitative Biology' , 'Quantitative Finance']

submission = pd.DataFrame({'ID': test_id})
submission = pd.concat([submission, pd.DataFrame(outputs, columns = label_cols)], axis=1)

submission.head()

submission.to_csv('av.csv', index=False)